<?php

declare(strict_types=1);

namespace AgencyPowerstack\ContaoBlogSyncBundle\Service;

use Contao\Dbafs;
use Contao\FilesModel;
use Contao\NewsArchiveModel;
use Contao\NewsModel;
use Doctrine\DBAL\Connection;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpKernel\KernelInterface;

/**
 * Imports or updates a blog post pushed from Agency Powerstack as a Contao tl_news entry.
 *
 * Responsibilities:
 *  - Create or update tl_news records identified by the external post ID
 *  - Download and register the featured image and content images via Contao DBAFS
 *  - Replace {{contao_image::N}} placeholders with native tl_content image elements
 *  - Store remaining HTML segments as tl_content html elements
 *
 * All file I/O is wrapped defensively; a failed image download never aborts the
 * overall import. Content elements are written inside a DB transaction so a partial
 * failure cannot leave a news entry with no body content.
 */
final class BlogImporter
{
    public function __construct(
        private readonly LoggerInterface $logger,
        private readonly KernelInterface $kernel,
        private readonly Connection $connection,
    ) {
    }

    /**
     * Imports a single blog post into the given news archive.
     *
     * @param array<string, mixed> $blogData  Validated push payload from the backend.
     * @param int                  $archiveId Target tl_news_archive ID.
     *
     * @return NewsModel|null The saved news model, or null if the import failed.
     */
    public function importBlog(array $blogData, int $archiveId): ?NewsModel
    {
        try {
            $archive = NewsArchiveModel::findByPk($archiveId);
            if (!$archive) {
                $this->logger->error("News archive with ID {$archiveId} not found");
                return null;
            }

            $externalId = (string) ($blogData['id'] ?? '');
            if ($externalId === '') {
                $this->logger->error('Blog has no ID, skipping');
                return null;
            }

            // Sanitize the external ID for use in file-system paths.
            // This prevents path traversal if a malicious ID like "../../etc" is pushed.
            $safePostId = preg_replace('/[^a-zA-Z0-9_-]/', '-', $externalId);

            // Check whether the blog was already imported (by external ID)
            $existingNews = NewsModel::findOneBy(['externalId=?'], [$externalId]);
            $isUpdate     = ($existingNews !== null);

            if ($isUpdate) {
                $this->logger->info("Blog {$externalId} already imported, updating...");
                $news = $existingNews;
            } else {
                $news        = new NewsModel();
                $news->tstamp = time();
            }

            // Base fields
            $news->pid      = $archiveId;
            $news->headline = $blogData['title'] ?? 'Untitled';
            $news->author   = 0;

            if (!$isUpdate) {
                $news->alias = $this->generateAlias($blogData['title'] ?? 'untitled');
            }

            // Timestamps
            $createdAt  = !empty($blogData['createdAt']) ? strtotime($blogData['createdAt']) : time();
            $news->date = $createdAt;
            $news->time = $createdAt;

            // Full HTML content – prefer targetSystemCode (Contao-specific variant generated by the AI)
            $rawHtml = $blogData['targetSystemCode'] ?? $blogData['htmlContent'] ?? '';

            // Strip <img> wrappers around {{contao_image::N}} placeholders so that
            // preg_split() in updateContentElements() produces clean HTML segments
            $rawHtml = $this->normalizeImagePlaceholders($rawHtml);

            // Register all content images and build an index → binary-UUID map
            $imageUuids = $this->collectContentImageUuids(
                $blogData['contentImageUrls'] ?? [],
                $safePostId
            );

            // Teaser: truncated plain text (max 300 chars) derived from textContent
            $news->teaser = $this->buildTeaser($blogData['textContent'] ?? '', $rawHtml);

            // Publication status
            $news->published = (($blogData['status'] ?? '') === 'PUBLISH') ? 1 : 0;

            // External reference ID
            $news->externalId = $externalId;

            // Featured image
            if (!empty($blogData['postImageUrl'])) {
                $imageUuid = $this->ensureImageRegistered(
                    $blogData['postImageUrl'],
                    $safePostId,
                    'featured'
                );
                if ($imageUuid !== null) {
                    $news->addImage  = '1';
                    $news->singleSRC = $imageUuid;
                }
            }

            // SEO meta
            if (!empty($blogData['metaDescription'])) {
                $news->description = $blogData['metaDescription'];
            }
            if (!empty($blogData['title'])) {
                $news->pageTitle = $blogData['title'];
            }

            $news->save();

            // Write tl_content elements (html + image) inside a transaction
            $this->updateContentElements((int) $news->id, $rawHtml, $imageUuids);

            $this->logger->info("Successfully imported blog: {$news->headline} (ID: {$news->id})");

            return $news;

        } catch (\Throwable $e) {
            $this->logger->error('Error importing blog: ' . $e->getMessage());
            return null;
        }
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Builds the teaser text (max 300 chars) from plain-text content.
     * Falls back to stripping HTML tags from the raw HTML if no plain text is available.
     */
    private function buildTeaser(string $textContent, string $htmlFallback): string
    {
        $text = trim($textContent);

        if ($text === '') {
            $text = trim(strip_tags($htmlFallback));
        }

        if (mb_strlen($text) > 300) {
            $text = mb_substr($text, 0, 297) . '...';
        }

        return $text;
    }

    /**
     * Deletes existing auto-generated tl_content entries for the given news ID and
     * re-creates them from the raw HTML by alternating between html and image elements,
     * splitting at {{contao_image::N}} placeholders.
     *
     * The entire operation runs in a DB transaction: if any INSERT fails the DELETE is
     * rolled back and the news entry retains its previous content elements.
     *
     * @param array<int, string> $imageUuids  Map of placeholder index → binary UUID.
     */
    private function updateContentElements(int $newsId, string $rawHtml, array $imageUuids): void
    {
        try {
            $this->connection->transactional(function () use ($newsId, $rawHtml, $imageUuids): void {
                $this->connection->delete('tl_content', [
                    'pid'    => $newsId,
                    'ptable' => 'tl_news',
                ]);

                if (trim($rawHtml) === '') {
                    return;
                }

                // Split at {{contao_image::N}} placeholders; capture the index via PREG_SPLIT_DELIM_CAPTURE
                $parts   = preg_split('/\{\{contao_image::(\d+)\}\}/', $rawHtml, -1, PREG_SPLIT_DELIM_CAPTURE);
                $sorting = 128;
                $i       = 0;
                $count   = count($parts);

                while ($i < $count) {
                    // Even token: HTML segment
                    $htmlSegment = $parts[$i];
                    // Escape any remaining Contao insert tags so they are not parsed on the frontend
                    $safeHtml = str_replace(['{{', '}}'], ['&#123;&#123;', '&#125;&#125;'], $htmlSegment);

                    if (trim($safeHtml) !== '') {
                        $this->connection->insert('tl_content', [
                            'pid'       => $newsId,
                            'ptable'    => 'tl_news',
                            'tstamp'    => time(),
                            'type'      => 'html',
                            'html'      => $safeHtml,
                            'invisible' => 0,
                            'sorting'   => $sorting,
                        ]);
                        $sorting += 128;
                    }
                    $i++;

                    // Odd token: image placeholder index (captured delimiter)
                    if ($i < $count) {
                        $index = (int) $parts[$i];
                        if (isset($imageUuids[$index])) {
                            $this->connection->insert('tl_content', [
                                'pid'       => $newsId,
                                'ptable'    => 'tl_news',
                                'tstamp'    => time(),
                                'type'      => 'image',
                                'singleSRC' => $imageUuids[$index],
                                // 1200 px wide, proportional scaling via Contao's ResizeCalculator.
                                // A width > 0 ensures the image processor generates a /assets/images/... URL.
                                'size'      => serialize([1200, 0, 'proportional']),
                                'floating'  => 'above',
                                'invisible' => 0,
                                'sorting'   => $sorting,
                            ]);
                            $sorting += 128;
                        }
                        $i++;
                    }
                }

                $this->logger->info("tl_content elements created for news {$newsId} (sorting up to " . ($sorting - 128) . ')');
            });
        } catch (\Throwable $e) {
            $this->logger->error("tl_content update failed for news {$newsId}: " . $e->getMessage());
        }
    }

    /**
     * Normalises {{contao_image::N}} placeholders in the HTML produced by the AI.
     *
     * The AI wraps placeholders inside <img src="{{...}}"> and optional <figure>/<p>
     * elements. This method extracts bare placeholders so that preg_split() in
     * updateContentElements() can produce clean HTML segments without broken tags.
     *
     * Steps:
     *  1. <img src="{{contao_image::N}}" ...> → {{contao_image::N}}
     *  2. <figure>...(placeholder + optional figcaption)...</figure> → {{contao_image::N}}
     *  3. <p>...(placeholder only)...</p> → {{contao_image::N}}
     */
    private function normalizeImagePlaceholders(string $html): string
    {
        // 1. Extract placeholder from <img src="...">
        $html = preg_replace(
            '/<img\b[^>]*\bsrc="(\{\{contao_image::\d+\}\})"[^>]*\/?>/i',
            '$1',
            $html
        );

        // 2. Strip <figure> wrapper (with optional figcaption)
        $html = preg_replace(
            '/<figure\b[^>]*>\s*(\{\{contao_image::\d+\}\})\s*(?:<figcaption\b[^>]*>.*?<\/figcaption>\s*)?<\/figure>/si',
            '$1',
            $html
        );

        // 3. Strip <p> wrapper
        $html = preg_replace(
            '/<p\b[^>]*>\s*(\{\{contao_image::\d+\}\})\s*<\/p>/si',
            '$1',
            $html
        );

        return $html;
    }

    /**
     * Registers all content images and returns a map of placeholder index → binary UUID.
     *
     * @param array<int|string, string> $imageUrls   Ordered list of image URLs from the backend.
     * @param string                    $safePostId  Sanitized post ID (used as the target directory name).
     *
     * @return array<int, string>  Map of index → binary UUID (only for successfully registered images).
     */
    private function collectContentImageUuids(array $imageUrls, string $safePostId): array
    {
        $uuids = [];
        foreach ($imageUrls as $index => $imageUrl) {
            if (empty($imageUrl)) {
                continue;
            }
            $uuid = $this->ensureImageRegistered($imageUrl, $safePostId, 'content-' . $index);
            if ($uuid !== null) {
                $uuids[(int) $index] = $uuid;
            }
        }
        return $uuids;
    }

    /**
     * Ensures that a remote image exists locally and is registered in the Contao DBAFS.
     *
     * If the computed target path already exists in tl_files the existing UUID is returned
     * without downloading the file again. Otherwise the image is downloaded, written
     * atomically (temp file → rename to avoid partial files on failure) and registered
     * via Dbafs::addResource().
     *
     * @param string $imageUrl   Full URL of the remote image.
     * @param string $safePostId Sanitized post ID (used as the directory name under files/blog-images/).
     * @param string $suffix     Suffix appended to the filename (e.g. "featured", "content-0").
     *
     * @return string|null  Binary UUID of the registered file, or null on failure.
     */
    private function ensureImageRegistered(string $imageUrl, string $safePostId, string $suffix): ?string
    {
        try {
            $projectDir = $this->kernel->getProjectDir();
            $targetDir  = 'files/blog-images/' . $safePostId;
            $extension  = $this->guessExtension($imageUrl);
            $filename   = $this->guessFilename($imageUrl, $suffix) . '.' . $extension;
            $targetPath = $targetDir . '/' . $filename;

            // Already registered? Return the existing UUID without downloading.
            $existingFile = FilesModel::findByPath($targetPath);
            if ($existingFile !== null) {
                $this->logger->info("Image already registered in Contao: {$targetPath}");
                return $existingFile->uuid;
            }

            // Create target directory if necessary
            $fullTargetDir = $projectDir . '/' . $targetDir;
            if (!is_dir($fullTargetDir) && !mkdir($fullTargetDir, 0755, true) && !is_dir($fullTargetDir)) {
                $this->logger->error("Could not create image directory: {$fullTargetDir}");
                return null;
            }

            // Download and validate the image
            $imageContent = $this->downloadFile($imageUrl);
            if ($imageContent === null) {
                return null;
            }

            // Write atomically: temp file → rename (avoids leaving a partial file on failure)
            $fullTargetPath = $projectDir . '/' . $targetPath;
            $tmpPath        = $fullTargetPath . '.tmp.' . bin2hex(random_bytes(4));
            if (file_put_contents($tmpPath, $imageContent) === false) {
                $this->logger->error("Could not write image temp file: {$tmpPath}");
                return null;
            }
            rename($tmpPath, $fullTargetPath);

            // Register with Contao DBAFS
            Dbafs::addResource($targetPath);

            $file = FilesModel::findByPath($targetPath);
            if ($file !== null) {
                $this->logger->info("Image registered in Contao: {$targetPath}");
                return $file->uuid;
            }

            return null;

        } catch (\Throwable $e) {
            $this->logger->error('Error registering image: ' . $e->getMessage());
            return null;
        }
    }

    /**
     * Downloads a file from a URL and validates that the response is a known image format.
     *
     * Checks the HTTP status code and uses magic-byte inspection to reject non-image
     * responses (e.g. expired S3 presigned URLs returning XML error pages with HTTP 403).
     *
     * Note: SVG is intentionally excluded because SVG files may contain embedded
     * JavaScript and can be rendered directly by the browser, creating an XSS vector.
     * If SVG support is required in the future, add server-side sanitisation first.
     *
     * @return string|null  Raw image bytes, or null if the download or validation fails.
     */
    private function downloadFile(string $url): ?string
    {
        $this->logger->debug('Downloading image from: ' . substr($url, 0, 100));

        $context = stream_context_create([
            'http' => [
                'timeout'         => 30,
                'user_agent'      => 'ContaoBlogSync/1.0',
                'ignore_errors'   => true,
                'follow_location' => 1,
            ],
            'ssl' => [
                'verify_peer'      => true,
                'verify_peer_name' => true,
            ],
        ]);

        // $http_response_header is populated by PHP in the local scope after file_get_contents
        $content    = @file_get_contents($url, false, $context);
        $httpStatus = $http_response_header[0] ?? 'n/a';

        $this->logger->debug(sprintf(
            'Image response: %s, %d bytes',
            $httpStatus,
            is_string($content) ? strlen($content) : -1
        ));

        if (!is_string($content) || $content === '') {
            $this->logger->warning('Image download returned empty/false – likely a network error');
            return null;
        }

        // Reject non-2xx responses
        if (!empty($http_response_header) && !preg_match('#HTTP/[\d.]+\s+2\d\d#', $httpStatus)) {
            $this->logger->warning("Image download failed – HTTP: {$httpStatus}");
            return null;
        }

        if (!$this->isValidImageContent($content)) {
            $this->logger->warning(sprintf(
                'Downloaded content is not a valid image (%d bytes, starts: %s)',
                strlen($content),
                substr($content, 0, 32)
            ));
            return null;
        }

        return $content;
    }

    /**
     * Checks magic bytes to determine whether the content is a supported image format.
     *
     * Supported: JPEG, PNG, GIF, WebP, AVIF/HEIC (ISO BMFF).
     * SVG is deliberately excluded – see downloadFile() for the rationale.
     */
    private function isValidImageContent(string $content): bool
    {
        if (strlen($content) < 8) {
            return false;
        }

        return str_starts_with($content, "\xFF\xD8\xFF")       // JPEG
            || str_starts_with($content, "\x89PNG\r\n\x1a\n")  // PNG
            || str_starts_with($content, 'GIF8')               // GIF
            || str_starts_with($content, 'RIFF')               // WebP (RIFF....WEBP)
            || substr($content, 4, 4) === 'ftyp';              // AVIF / HEIC (ISO BMFF)
    }

    /**
     * Derives a human-readable filename from the URL path.
     * Falls back to $fallback when the URL contains only UUIDs/hashes (32+ hex chars).
     */
    private function guessFilename(string $url, string $fallback): string
    {
        $path = parse_url($url, PHP_URL_PATH);
        if ($path) {
            $name = pathinfo($path, PATHINFO_FILENAME);
            // Skip UUID/hash-only names (e.g. S3 object keys)
            if ($name !== '' && strlen($name) < 100 && !preg_match('/^[a-f0-9\-]{32,}$/i', $name)) {
                return preg_replace('/[^a-zA-Z0-9_-]/', '-', $name);
            }
        }

        return $fallback;
    }

    /**
     * Derives the file extension from the URL path.
     * Returns 'jpg' as a safe default when the extension cannot be determined.
     */
    private function guessExtension(string $url): string
    {
        $path = parse_url($url, PHP_URL_PATH);
        if ($path) {
            $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
            if (in_array($ext, ['jpg', 'jpeg', 'png', 'gif', 'webp', 'avif'], true)) {
                return $ext;
            }
        }
        return 'jpg';
    }

    /**
     * Generates a unique URL alias for a new news entry.
     *
     * Uses Contao's StringUtil::standardize() for consistent slug generation and
     * appends an incrementing counter when the desired alias is already taken.
     *
     * Note: There is a theoretical race condition if two imports with the same title
     * run concurrently. This is acceptable given the sequential push flow used by
     * the Agency Powerstack workers.
     */
    private function generateAlias(string $title): string
    {
        $alias     = \Contao\StringUtil::standardize(\Contao\StringUtil::restoreBasicEntities($title));
        $testAlias = $alias;
        $count     = 0;

        while (NewsModel::findByAlias($testAlias)) {
            $count++;
            $testAlias = $alias . '-' . $count;
        }

        return $testAlias;
    }
}
