services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AgencyPowerstack\ContaoBlogSyncBundle\:
    resource: '../src/'
    exclude:
      - '../src/ContaoManager/'
      - '../src/Resources/'
      - '../src/DependencyInjection/'

  AgencyPowerstack\ContaoBlogSyncBundle\Service\ApiClient:
    arguments:
      $logger: '@monolog.logger'
      $apiUrl: '%blog_sync.frontend_url%/backend/contao/'

  AgencyPowerstack\ContaoBlogSyncBundle\Service\BlogImporter:
    arguments:
      $logger: '@monolog.logger'

  AgencyPowerstack\ContaoBlogSyncBundle\Command\SyncBlogsCommand:
    tags:
      - { name: 'console.command' }

  AgencyPowerstack\ContaoBlogSyncBundle\Cron\BlogSyncCron:
    public: true

  AgencyPowerstack\ContaoBlogSyncBundle\Controller\ConnectCallbackController:
    tags:
      - { name: 'controller.service_arguments' }

  AgencyPowerstack\ContaoBlogSyncBundle\Controller\SyncTriggerController:
    tags:
      - { name: 'controller.service_arguments' }

  AgencyPowerstack\ContaoBlogSyncBundle\Controller\DisconnectController:
    tags:
      - { name: 'controller.service_arguments' }

  AgencyPowerstack\ContaoBlogSyncBundle\EventListener\AccountDeleteListener:
    public: true
    arguments:
      $apiClient: '@AgencyPowerstack\ContaoBlogSyncBundle\Service\ApiClient'
      $connection: '@doctrine.dbal.default_connection'
      $logger: '@monolog.logger'
